site_name: "SmartJob Python Library"
repo_url: https://github.com/fabien-marty/smartjob

theme:
  name: "material"

plugins:
- search
- awesome-pages
- mkdocstrings:
    handlers:
      python:
        options:
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          parameter_headings: false


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
